### ISSUE TITLE
Noise values displayed improperly with two APAs

### ISSUE THREAD

**Issue by wesketchum** [DUNE-DAQ/dqm#128]
In v3.2.0, seeing something like 

![Screen Shot 2022-10-18 at 1 22 27 PM](https://user-images.githubusercontent.com/5596636/196938177-47511460-3656-402c-98e7-ba6bb82a6a0f.png)

Channel numbering looks ok, and displays for the readout apps look ok.

Should make a fix for `patch/v3.2.x` branch.

**Comment by jmcarcell** [comment]
Fixed in https://github.com/DUNE-DAQ/daqconf/pull/253
