### ISSUE TITLE
Warning messages seen from the DQM-related part of 3ru_3df_multirun_test.py

### ISSUE THREAD

**Issue by bieryAtFnal** [DUNE-DAQ/dqm#90]
This was seen with the N22-05-19 nightly release with the develop branch of daqconf and the kbiery/integtest_updates_for3.0 branch in dfmodules.

Problem(s) found in logfile /tmp/pytest-of-biery/pytest-639/run0/log_dqm0_ru_3337.txt:
2022-May-19 11:39:52,888 ERROR [dunedaq::iomanager::connection::ConnectionId dunedaq::iomanager::IOManager::ref_to_id(const dunedaq::iomanager::connection::ConnectionRef&) at /cvmfs/dunedaq-development.opensciencegrid.org/spack-nightly/N22-05-19/spack-0.17.1/opt/spack/gcc-8.2.0/iomanager-N22-05-19-6b4fckfpqeukxlyoqkxtoc5tyurvvb6j/include/iomanager/IOManager.hpp:216] Connection with uid timesync_0 not found!

2022-May-19 11:39:52,888 ERROR [void dunedaq::cmdlib::CommandFacility::handle_command(const cmdobj_t&, dunedaq::cmdlib::cmd::CommandReply) at /tmp/root/spack-stage/spack-stage-cmdlib-N22-05-19-evkz6sywhalbysleudv5sq7v64v4g7ms/spack-src/src/CommandFacility.cpp:64] Execution of command failed: Caught ers::Issue

	was caused by: 2022-May-19 11:39:52,888 ERROR [void dunedaq::appfwk::DAQModuleManager::dispatch_one_match_only(dunedaq::cmdlib::cmd::CmdId, const string&, const dataobj_t&) at /tmp/root/spack-stage/spack-stage-appfwk-N22-05-19-z6vqmiaqc3zzfaujl7vqpjzwafncfly6/spack-src/src/detail/DAQModuleManager.hxx:199] Command start was not executed correctly by: dqmprocessor,

**Comment by dingp** [comment]
@eflumerf Does this need a similar fix as https://github.com/DUNE-DAQ/daqconf/pull/60

**Comment by eflumerf** [comment]
Also needs https://github.com/DUNE-DAQ/daqconf/pull/62
